version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms
    ports:
      - "3306:3306"
    network_mode: "host"
#    networks:
#      - lms_internal
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -proot" ]
      interval: 2s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    network_mode: "host"
#    networks:
#      - lms_internal
    environment:
      JDBC_URL: "jdbc:mysql://host.docker.internal:3306/lms?user=root&password=root&useSSL=false"
#    network_mode: "host"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    depends_on:
      mysql:
        condition: service_healthy

#networks:
#  lms_internal:
#    driver: bridge

