version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms
    ports:
      - "3308:3306"
    # network_mode: "host"
    networks:
      - lms_internal
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - lms_internal
    environment:
      JDBC_URL: "jdbc:mysql://127.0.0.1:3306/lms?user=root&password=root&useSSL=false"
    network_mode: "host"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql

networks:
  lms_internal:
    driver: bridge

