version: '3'
services:
#  mysql:
#    image: mysql:latest
#    environment:
#      MYSQL_HOST: localhost
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: lms
#    ports:
#      - "3307:3306"
#    volumes:
#      - ./mysql-init:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: "jdbc:mysql://host.docker.internal:3306/lms_server?user=root&password=manhblue"
    extra_hosts:
      - "host.docker.internal:host-gateway"
